branches:
  - name: main
  - name: alpha
    prerelease: true
  # - name: beta
  #   prerelease: true

# also run `npm dist-tag add wordpressed@0.1.0-alpha.XXX latest` to update latest.
# (could be an exec step!)

plugins:
  - '@semantic-release/commit-analyzer'

  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      presetConfig:
        types:
          # same order as node_modules/conventional-commit-types
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: docs
            section: Documentation
            #hidden: true
          - type: style
            section: Styles
            #hidden: true
          - type: refactor
            section: Code Refactoring
            #hidden: true
          - type: perf
            section: Performance Improvements
          - type: test
            section: Tests
            #hidden: true
          - type: build
            section: Build System
            #hidden: true
          - type: ci
            section: Continuous Integration
            #hidden: true
          - type: chore
            section: Miscellaneous Chores
            #hidden: true
          - type: revert
            section: Reverts

  - - '@semantic-release/changelog'
    - changelogTitle: |
        # Changelog

        _All notable changes to this project will be documented in this file. See [Conventional Commits](https://www.conventionalcommits.org/) for commit guidelines._

  - '@semantic-release/github'

  - '@semantic-release/npm'

  - '@semantic-release/git'
