branches:
  - name: main
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogTitle: |
        # Changelog

        _All notable changes to this project will be documented in this file. See [Conventional Commits](https://www.conventionalcommits.org/) for commit guidelines._

  - '@semantic-release/git'
  - '@semantic-release/github'
  - '@semantic-release/npm'

dryRun: true
